name: Setup Infrastructure
on:
  push:
    branches: [main]
    paths:
      - 'ansible/**'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: T97iqqzC1Y11CNTRL-kVangMo5sj11CNTRL
          audience: api.tailscale.com/T97iqqzC1Y11CNTRL-kVangMo5sj11CNTRL
          tags: tag:ci

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible playbook
        working-directory: ansible
        env:
          ANSIBLE_CONFIG: ansible.cfg
        run: ansible-playbook playbook.yml
